name: revolt_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies: 
  http: ^0.13.4
  json_annotation: ^4.3.0
  rxdart: ^0.27.3
  


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  json_serializable: ^6.0.1
  build_runner: ^2.1.5
  mockito: ^5.0.16
